/* ------------------------------------------------------------------ */
/*  Package.json patcher                                               */
/*                                                                     */
/*  Replaces only previously generated languageModelTools entries,      */
/*  preserving manually-added tools via sidecar state tracking.         */
/* ------------------------------------------------------------------ */

import * as fs from 'fs';
import * as path from 'path';
import type { IScannedTool } from './scanner';

/* ------------------------------------------------------------------ */
/*  Constants                                                          */
/* ------------------------------------------------------------------ */

/**
 * Legacy start marker used by early auto-generated blocks.
 */
export const MARKER_START = '____AUTOGEN_TOOLS_START____';

/**
 * Legacy end marker used by early auto-generated blocks.
 */
export const MARKER_END   = '____AUTOGEN_TOOLS_END____';

/**
 * Sidecar state file storing legacy generated tool ownership.
 */
export const AUTOGEN_STATE_FILE = '.mcp-scanner.state.json';

/* ------------------------------------------------------------------ */
/*  Result type                                                        */
/* ------------------------------------------------------------------ */

export interface IPatchResult {
  /**
   * Whether patch operation completed successfully.
   */
  ok: boolean;

  /**
   * Human-readable status message.
   */
  message: string;
}

/**
 * Optional patching behavior switches.
 */
export interface IPatchOptions {
  /**
   * When set, patching is scoped to tools carrying this tag.
   */
  toolTag?: string;
}

/**
 * Legacy ownership state schema.
 */
interface IAutoGenState {
  /**
   * State schema version.
   */
  version: 1;

  /**
   * Tool names generated in the previous run.
   */
  generatedToolNames: string[];
}

/**
 * Type guard for plain JSON objects.
 *
 * @param value Unknown value.
 * @returns `true` when value is a non-array object.
 */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Extract a tool name from an unknown `languageModelTools` entry.
 *
 * @param entry Unknown entry from package.json.
 * @returns Tool name when available.
 */
function getToolName(entry: unknown): string | undefined {
  if (!isRecord(entry)) {
    return undefined;
  }
  const name = entry.name;
  return typeof name === 'string' ? name : undefined;
}

/**
 * Check whether a tool entry has a specific tag.
 *
 * @param entry Unknown tool entry.
 * @param tag Required tag.
 * @returns `true` when entry has `tags` including `tag`.
 */
function hasToolTag(entry: unknown, tag: string): boolean {
  if (!isRecord(entry)) {
    return false;
  }

  const tags = entry.tags;
  if (!Array.isArray(tags)) {
    return false;
  }

  return tags.some((value) => typeof value === 'string' && value === tag);
}

/**
 * Parse legacy state content from disk.
 *
 * @param raw Raw JSON state text.
 * @returns Previously generated tool names.
 */
function parseStateContent(raw: string): string[] {
  try {
    const parsed: unknown = JSON.parse(raw);
    if (!isRecord(parsed)) {
      return [];
    }
    const names = parsed.generatedToolNames;
    if (!Array.isArray(names)) {
      return [];
    }
    return names.filter((n): n is string => typeof n === 'string');
  } catch {
    return [];
  }
}

/**
 * Serialize legacy state content.
 *
 * @param generatedToolNames Tool names generated by current run.
 * @returns Formatted state JSON text.
 */
function makeStateContent(generatedToolNames: string[]): string {
  const uniqueNames = Array.from(new Set(generatedToolNames));
  const state: IAutoGenState = {
    version: 1,
    generatedToolNames: uniqueNames,
  };
  return `${JSON.stringify(state, null, 2)}\n`;
}

/* ------------------------------------------------------------------ */
/*  Core patching logic (operates on raw string)                       */
/* ------------------------------------------------------------------ */

/**
 * Patch the raw content of a package.json string, replacing only
 * previously generated tools.
 *
 * @param raw The current package.json text.
 * @param generatedTools The tools to inject.
 * @param previousGeneratedToolNames The tool names generated in the previous run.
 * @param options Optional patching switches.
 * @returns The new package.json text and a status message.
 */
export function patchPackageJsonContent(
  raw: string,
  generatedTools: IScannedTool[],
  previousGeneratedToolNames: string[] = [],
  options: IPatchOptions = {},
): { content: string; result: IPatchResult; nextGeneratedToolNames: string[] } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return {
      content: raw,
      result: { ok: false, message: 'package.json is not valid JSON.' },
      nextGeneratedToolNames: previousGeneratedToolNames,
    };
  }

  if (!isRecord(parsed)) {
    return {
      content: raw,
      result: { ok: false, message: 'package.json root must be a JSON object.' },
      nextGeneratedToolNames: previousGeneratedToolNames,
    };
  }

  const root = parsed as Record<string, unknown>;

  const contributesRaw = root.contributes;
  const contributes: Record<string, unknown> = isRecord(contributesRaw) ? contributesRaw : {};

  const existingArrayRaw = contributes.languageModelTools;
  const existingTools = Array.isArray(existingArrayRaw) ? existingArrayRaw : [];

  const startMarkerIndex = existingTools.findIndex((entry) => entry === MARKER_START);
  const endMarkerIndex = existingTools.findIndex((entry, index) => index > startMarkerIndex && entry === MARKER_END);
  const toolTag = options.toolTag?.trim();

  const previousGeneratedSet = new Set(previousGeneratedToolNames);
  const manualTools: unknown[] = [];

  for (let i = 0; i < existingTools.length; i++) {
    const entry = existingTools[i];

    if (entry === MARKER_START || entry === MARKER_END) {
      continue;
    }

    const insideLegacyBlock = startMarkerIndex !== -1 && endMarkerIndex !== -1 && i > startMarkerIndex && i < endMarkerIndex;
    if (insideLegacyBlock) {
      continue;
    }

    if (toolTag && hasToolTag(entry, toolTag)) {
      continue;
    }

    const entryName = getToolName(entry);
    if (!toolTag && entryName && previousGeneratedSet.has(entryName)) {
      continue;
    }

    manualTools.push(entry);
  }

  const generatedEntries: unknown[] = generatedTools.map((tool) => {
    if (!toolTag) {
      return { ...tool };
    }

    const mergedTags = Array.from(new Set([...(tool.tags ?? []), toolTag, 'generated-by-mcp-scanner']));
    return {
      ...tool,
      tags: mergedTags,
    };
  });
  contributes.languageModelTools = [...manualTools, ...generatedEntries];

  root.contributes = contributes;

  const nextGeneratedToolNames = generatedTools.map((tool) => tool.name);

  return {
    content: `${JSON.stringify(root, null, 2)}\n`,
    result: {
      ok: true,
      message: toolTag
        ? `Patched package.json with ${generatedTools.length} auto-generated tool(s) for tag '${toolTag}'.`
        : `Patched package.json with ${generatedTools.length} auto-generated tool(s).`,
    },
    nextGeneratedToolNames,
  };
}

/* ------------------------------------------------------------------ */
/*  File-system convenience (for CLI and Node.js usage)                */
/* ------------------------------------------------------------------ */

/**
 * Patch a package.json file on disk.
 *
 * @param packageJsonPath Absolute path to package.json.
 * @param generatedTools The tools to inject.
 * @param options Optional patching switches.
 * @returns Patch operation result.
 */
export function patchPackageJsonFile(
  packageJsonPath: string,
  generatedTools: IScannedTool[],
  options: IPatchOptions = {},
): IPatchResult {
  if (!fs.existsSync(packageJsonPath)) {
    return { ok: false, message: `File not found: ${packageJsonPath}` };
  }

  const stateFilePath = path.join(path.dirname(packageJsonPath), AUTOGEN_STATE_FILE);

  let previousGeneratedToolNames: string[] = [];
  if (fs.existsSync(stateFilePath)) {
    previousGeneratedToolNames = parseStateContent(fs.readFileSync(stateFilePath, 'utf-8'));
  }

  const raw = fs.readFileSync(packageJsonPath, 'utf-8');
  const { content, result, nextGeneratedToolNames } = patchPackageJsonContent(
    raw,
    generatedTools,
    previousGeneratedToolNames,
    options,
  );

  if (result.ok) {
    fs.writeFileSync(packageJsonPath, content, 'utf-8');
    if (!options.toolTag) {
      fs.writeFileSync(stateFilePath, makeStateContent(nextGeneratedToolNames), 'utf-8');
    }
  }

  return result;
}
